services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: quizstack_app
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - quizstack_network

  db:
    image: mysql:8.0
    container_name: quizstack_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizstack_db
      MYSQL_USER: quizstack_user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - quizstack_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: quizstack_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: quizstack_user
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - quizstack_network

volumes:
  db_data:

networks:
  quizstack_network:
    driver: bridge